// lib/modules/localization.dart

class AppLocalizations {
  final String lang;
  AppLocalizations(this.lang);

  static final Map<String, Map<String, String>> _localizedValues = {
    'vi': {
      'app_title': 'Tối ưu hóa định tuyến mạng',
      'sidebar_home': 'Trang chủ',
      'sidebar_config': 'Cấu hình mạng',
      'sidebar_diag': 'Chẩn đoán mạng',
      'sidebar_logs': 'Nhật ký logs',
      'sidebar_about': 'Thông tin ứng dụng',
      'top_bar_title': 'Kiểm tra chẩn đoán kết nối',
      'admin_mode': 'ADMIN MODE',
      'user_mode': 'USER MODE (REQUIRES ADMIN)',
      'home_welcome': 'Sẵn sàng tối ưu hóa định tuyến mạng dual-NIC',
      'home_welcome_sub':
          'Công cụ cấu hình tự động bỏ qua Default Route trên LAN adapter và cấu hình các route vĩnh viễn cho máy tính.',
      'home_btn_fix': 'BẮT ĐẦU FIX',
      'home_steps_title': 'Quy trình các bước thực hiện',
      'config_title': 'Cấu hình thông số định tuyến',
      'config_desc':
          'Thiết lập các IP gateway và subnet mạng để ứng dụng áp dụng chính xác cho Windows.',
      'config_internet_gw': 'Gateway Internet chính (INTERNET_GW)',
      'config_backup_gw': 'Gateway Backup (BACKUP_GW)',
      'config_lan_gw': 'Gateway mạng LAN (LAN_GW)',
      'config_lan_net': 'Dải mạng LAN đích (LAN_NET)',
      'config_lan_mask': 'Subnet Mask của LAN (LAN_MASK)',
      'config_log_path': 'Đường dẫn tệp ghi logs',
      'config_custom_routes': 'Các dải đích định tuyến bổ sung',
      'config_lan_dest': 'Dải mạng LAN đích (IP/Mask)',
      'config_lan_dest_desc':
          'Dải mạng LAN nội bộ được định tuyến qua LAN gateway.',
      'config_internet_dest': 'Dải Internet bypass (IP/Mask)',
      'config_internet_dest_desc':
          'Dải mạng Internet đặc thù được ép định tuyến qua Internet gateway.',
      'config_recovery_title': 'Quản lý điểm khôi phục & Lưu trữ cấu hình',
      'config_recovery_win': 'Điểm khôi phục Windows',
      'config_recovery_win_desc':
          'Lưu lại cấu hình card mạng và bảng định tuyến hiện tại của Windows để phục hồi khi cần thiết.',
      'config_btn_create': 'Tạo mới',
      'config_btn_restore': 'Khôi phục',
      'config_app_json': 'Cấu hình ứng dụng (.json)',
      'config_app_json_desc':
          'Xuất các cấu hình dải mạng và gateway hiện tại thành file JSON, hoặc nhập lại cấu hình từ file đã lưu.',
      'config_btn_export': 'Xuất cấu hình JSON',
      'config_btn_import': 'Nhập cấu hình JSON',
      'config_btn_reset': 'Đặt lại mặc định',
      'config_btn_save': 'Lưu cấu hình',
      'config_add_route': 'Thêm dải mạng',
      'config_dialog_admin_req': 'Cần quyền Administrator',
      'config_dialog_backup_success':
          'Bản sao lưu cấu hình định tuyến hiện tại đã được tạo thành công.',
      'config_dialog_backup_fail':
          'Không thể xuất cấu hình. Vui lòng kiểm tra file log hoặc chạy quyền Admin.',
      'config_dialog_restore_success':
          'Hệ thống định tuyến mạng đã được đưa về trạng thái khôi phục đã chọn.',
      'config_dialog_restore_fail':
          'Đã xảy ra lỗi khi khôi phục. Vui lòng kiểm tra nhật ký log.',
      'config_dialog_export_success': 'Tệp cấu hình đã được lưu tại:\n',
      'config_dialog_export_fail': 'Không thể ghi tệp cấu hình vào đĩa.',
      'config_dialog_import_success': 'Cấu hình mới đã được tải và cập nhật.',
      'config_dialog_import_fail':
          'Tệp tin không đúng định dạng JSON cấu hình hợp lệ.',
      'config_dialog_save_success':
          'Các thông số định tuyến mới đã được lưu thành công vào config.json và config.ini.',
      'config_dialog_save_title': 'Đã lưu cấu hình',
      'config_btn_detect': 'Tự động nhận diện',
      'config_detect_success': 'Đã tự động nhận diện và cập nhật gateway!',
      'config_detect_fail': 'Không thể tự động nhận diện gateway hoạt động.',
      'diag_title': 'Trình chẩn đoán & Thực thi nhanh',
      'diag_desc':
          'Chạy kiểm tra thủ công hoặc thực hiện các lệnh làm sạch hệ thống mạng nhanh chóng.',
      'diag_btn_route': 'Xem bảng Route hiện tại',
      'diag_btn_route_desc':
          'In bảng định tuyến IPv4 đang hoạt động của hệ thống.',
      'diag_btn_flush': 'Xóa DNS & ARP Cache',
      'diag_btn_flush_desc':
          'Giải phóng cache DNS và bảng phân giải địa chỉ vật lý ARP.',
      'diag_btn_tailscale': 'Trạng thái Tailscale',
      'diag_btn_tailscale_desc':
          'Kiểm tra trạng thái kết nối và các thiết bị trong mạng Tailscale.',
      'diag_ping': 'Ping Test:',
      'diag_terminal': 'OUTPUT TERMINAL',
      'diag_table_title': 'BẢNG ĐỊNH TUYẾN IPv4 CHI TIẾT',
      'diag_btn_raw': 'Hiển thị mã thô',
      'diag_btn_table': 'Hiển thị dạng bảng',
      'diag_btn_copy': 'Sao chép kết quả',
      'logs_title': 'Nhật ký hoạt động hệ thống',
      'logs_desc': 'Xem các dòng logs hoạt động trực tiếp của ứng dụng.',
      'logs_btn_clear': 'Xóa màn hình',
      'logs_btn_copy': 'Sao chép Logs',
      'about_title': 'Giới thiệu ứng dụng',
      'about_desc_title': 'Mô tả dự án:',
      'about_details_title': 'THÔNG TIN CHI TIẾT DỰ ÁN',
      'about_name': 'Tên dự án',
      'about_tech': 'Công nghệ sử dụng',
      'about_managed': 'Quản lý bởi',
      'about_web': 'Trang web',
      'about_desc_detail': 'Mô tả chi tiết',
      'about_project_desc':
          'Ứng dụng này cung cấp giao diện đồ họa GUI tiên tiến để giải quyết triệt để lỗi xung đột default gateway khi máy tính kết nối đồng thời với hai mạng: Internet và mạng nội bộ công ty (LAN/Company). \n\nBằng cách cấu hình cài đặt "IgnoreDefaultRoutes" trên Network Interface index của card mạng LAN, Windows sẽ không tự động nhận default route sai từ DHCP của LAN. Ngoài ra, ứng dụng sẽ tạo các bản ghi định tuyến tĩnh vĩnh viễn (persistent routes) hướng lưu lượng mạng LAN qua gateway LAN chính xác và giữ các luồng mạng khác qua Gateway Internet.',
      'step_admin': 'Kiểm tra quyền Administrator',
      'step_lan_adapter': 'Bật IgnoreDefaultRoutes trên LAN card (172.21.x)',
      'step_metrics': 'Đặt Metric ưu tiên cho Network/Backup (192.168.x)',
      'step_flush': 'Làm mới ARP & DNS Cache',
      'step_clean': 'Dọn dẹp các Route cũ/sai',
      'step_persistent_routes': 'Inject các Route mới vĩnh viễn',
      'step_clean_lan_gw': 'Chặn Default Route qua LAN gateway lần cuối',
      'step_verify': 'Kiểm tra lại bảng Route',
      'step_ping_test': 'Kiểm tra Ping Internet (1.1.1.1)',
      'step_tailscale_login': 'Kiểm tra kết nối login.tailscale.com:443',
      'step_tailscale_status': 'Kiểm tra trạng thái Tailscale',
      'logs_btn_export': 'Xuất file Logs',
      'logs_copied_toast': 'Đã sao chép logs hệ thống',
      'logs_export_success_toast': 'Xuất logs thành công: ',
      'logs_export_fail_toast': 'Xuất logs thất bại',
      'logs_empty_toast': 'Không có log nào để xuất.',
      'logs_empty_placeholder': 'Chưa có log hệ thống nào.',
      'log_opt_start': '===== BẮT ĐẦU QUY TRÌNH TỐI ƯU HÓA ĐỊNH TUYẾN =====',
      'log_opt_end': '===== QUY TRÌNH TỐI ƯU HÓA HOÀN THÀNH =====',
      'log_engine_missing': 'Không tìm thấy platform engine.',
      'log_admin_required':
          'Ứng dung không được chạy với quyền Administrator. Vui lòng chạy lại bằng Run as administrator.',
      'log_admin_ok': 'Đã có quyền Administrator.',
      'log_lan_adapter_warn':
          'WARN: Không tìm thấy hoặc không cấu hình được LAN adapter {pattern}',
      'log_lan_adapter_ok':
          'Đã bật IgnoreDefaultRoutes & set metric 80 cho adapter {pattern}',
      'log_metrics_warn':
          'WARN: Không tìm thấy adapter {ip1} và {ip2} để set metric',
      'log_metrics_ok':
          'Đã đặt metric ưu tiên cho các adapter mạng Internet (metric 10/25)',
      'log_flush_ok': 'Đã làm mới ARP và DNS cache.',
      'log_clean_ok':
          'Đã xóa các route cũ/lỗi liên quan đến {internetGw} và {lanGw}',
      'log_persistent_warn':
          'Nạp route 0.0.0.0 qua {gw} metric 5 cảnh báo (Đã tồn tại?)',
      'log_persistent_ok':
          'Đã nạp route vĩnh viễn:\n  - Default route: 0.0.0.0/0 -> {internetGw} (Metric 5)\n  - Đã nạp {lanCount} route LAN (qua {lanGw})\n  - Đã nạp {internetCount} route Internet-Bypass (qua {internetGw}, Metric 2)',
      'log_clean_lan_gw_ok': 'Đã xóa mọi default route qua LAN gateway {gw}',
      'log_verify_warn':
          'WARN: Vẫn còn default route qua {gw}. Vui lòng chạy lại chương trình.',
      'log_verify_ok': 'Chính xác: Không còn default route qua {gw}.',
      'log_ping_warn':
          'WARN: Ping 1.1.1.1 thất bại. Vui lòng kiểm tra lại đường truyền.',
      'log_ping_ok': 'Ping 1.1.1.1 OK!\n{res}',
      'log_tailscale_conn_warn':
          'WARN: Không thể kết nối đến login.tailscale.com:443',
      'log_tailscale_conn_ok': 'Kết nối đến login.tailscale.com:443 OK!',
      'log_backup_start': '===== BẮT ĐẦU SAO LƯU CẤU HÌNH NET =====',
      'log_backup_ok':
          '===== SAO LƯU CẤU HÌNH NET THÀNH CÔNG: {timestamp} =====',
      'log_backup_fail': '===== SAO LƯU CẤU HÌNH NET THẤT BẠI =====',
      'log_restore_start':
          '===== BẮT ĐẦU KHÔI PHỤC CẤU HÌNH NET: {timestamp} =====',
      'log_restore_config_ok':
          '[OK] Đã khôi phục cấu hình ứng dụng từ bản sao lưu.',
      'log_restore_ok': '===== KHÔI PHỤC CẤU HÌNH NET THÀNH CÔNG =====',
      'log_restore_fail': '===== KHÔI PHỤC CẤU HÌNH NET THẤT BẠI =====',
      'log_import_ok': '[OK] Đã nhập cấu hình mới từ {path}',
      'log_export_ok': '[OK] Đã xuất cấu hình ra {path}',
      'log_load_config_ok': 'Tải cấu hình thành công từ config.json',
      'log_load_config_default':
          'Không tìm thấy config.json, sử dụng cấu hình mặc định.',
      'log_save_config_ok': 'Đã lưu cấu hình vào config.json và config.ini',
      'log_rollback_start':
          '===== BẮT ĐẦU TỰ ĐỘNG KHÔI PHỤC (ROLLBACK) CẤU HÌNH =====',
      'log_rollback_ok': '===== TỰ ĐỘNG KHÔI PHỤC (ROLLBACK) THÀNH CÔNG =====',
      'log_rollback_fail': '===== TỰ ĐỘNG KHÔI PHỤC (ROLLBACK) THẤT BẠI =====',
      'dialog_cancel': 'Hủy',
      'dialog_confirm': 'Xác nhận',
      'config_restore_defaults': 'Khôi phục mặc định hệ thống',
      'config_restore_defaults_desc':
          'Xóa mọi định tuyến tĩnh tự thêm, khôi phục card mạng về chế độ IP Metric tự động và tắt IgnoreDefaultRoutes.',
      'config_btn_restore_defaults': 'Khôi phục mặc định',
      'config_dialog_restore_defaults_title': 'Khôi phục mặc định hệ thống?',
      'config_dialog_restore_defaults_confirm':
          'Hành động này sẽ xóa tất cả các định tuyến tĩnh và khôi phục các thiết lập card mạng của Windows về mặc định hệ thống. Bạn có chắc chắn muốn tiếp tục?',
      'config_dialog_restore_defaults_success':
          'Đã khôi phục cài đặt mặc định mạng Windows thành công.',
      'config_dialog_restore_defaults_fail':
          'Khôi phục cài đặt mặc định thất bại. Vui lòng kiểm tra log để biết chi tiết.',
      'profile_title': 'Tùy chọn cấu hình & Cấu hình mạng (Profiles)',
      'profile_active': 'Cấu hình mạng hiện tại',
      'profile_default': 'Mặc định',
      'profile_tooltip_add': 'Tạo cấu hình mới',
      'profile_tooltip_delete': 'Xóa cấu hình này',
      'profile_create_title': 'Tạo cấu hình mới',
      'profile_create_label': 'Tên cấu hình mạng',
      'profile_create_hint': 'Ví dụ: Mạng văn phòng B',
      'auto_heal_title': 'Tự động giám sát & tối ưu định tuyến (Auto-Healing)',
      'auto_heal_desc':
          'Giám sát bảng định tuyến mỗi 30 giây. Tự động sửa lại nếu Windows đặt lại gateway khi mất mạng / đổi IP.',
      'auto_heal_badge': 'AUTO-HEAL ĐANG BẬT',
      'gateway_offline': 'Ngoại tuyến',
      'dashboard_live_console': 'Nhật ký thực thi gần nhất',
      'dashboard_console_placeholder':
          'Bấm "BẮT ĐẦU FIX" để chạy tối ưu hóa và xem nhật ký định tuyến trực tiếp tại đây...',
      'badge_dual_routing': 'DUAL NETWORK ROUTING',
      'node_internet_gw': 'Internet GW',
      'node_this_pc': 'Máy tính này',
      'node_lan_gw': 'LAN GW',
      'not_configured': 'Chưa thiết lập',
      'status_ready': 'SẴN SÀNG',
      'status_fixing': 'ĐANG TỐI ƯU...',
      'status_dual_active': 'DUAL ROUTE ACTIVE',
      'status_standby': 'STANDBY',
      'step_status_idle': 'Chờ',
      'step_status_running': 'Đang xử lý',
      'step_status_success': 'Hoàn tất',
      'step_status_warning': 'Cảnh báo',
      'step_status_error': 'Lỗi',
      'view_all_logs': 'Xem toàn bộ',
      'no_logs_placeholder':
          'Chưa có log phát sinh. Bấm "BẮT ĐẦU FIX" để chạy quy trình tối ưu.',
      'gateways_card_title': 'Cổng Gateway Định tuyến',
      'subnets_card_title': 'Dải mạng & Đường dẫn Log',
      'add_btn': 'Thêm',
      'btn_cancel': 'Hủy',
      'no_custom_routes': 'Chưa có dải định tuyến bổ sung nào.',
      'diag_quick_tools': 'Công cụ Chẩn đoán Nhanh',
      'diag_ping_hint':
          'Nhập IP/Host kiểm tra ping (ví dụ: 1.1.1.1 hoặc google.com)',
      'diag_btn_ping': 'Kiểm tra Ping',
      'diag_port_test': 'Test Cổng Máy chủ',
      'diag_restore_defaults': 'Khôi phục Mặc định Windows',
      'diag_routing_table': 'Bảng Định tuyến IPv4 Windows',
      'diag_terminal_idle_hint':
          'Sẵn sàng chạy chẩn đoán. Chọn một công cụ bên trên hoặc kiểm tra ping để xem kết quả tại đây.',
      'diag_terminal_running': 'Đang thực thi tác vụ chẩn đoán...',
      'diag_terminal_output_title': 'Kết quả chẩn đoán',
      'verify_suite_title': 'Đối soát & Chẩn đoán Mạng (Verify)',
      'verify_input_hint':
          'Nhập IP hoặc URL trang web (vd: 10.21.168.50, google.com, http://erp.local:8080)',
      'verify_btn': 'Verify Ngay',
      'verify_route_auto': 'Tự động',
      'verify_route_lan': 'Đi qua LAN',
      'verify_route_internet': 'Đi qua Internet',
      'verify_status_pass': 'KẾT NỐI TỐI ƯU',
      'verify_status_warning': 'CẦN KIỂM TRA THÊM',
      'verify_status_misrouted': 'CẢNH BÁO SAI GATEWAY',
      'verify_status_unreachable': 'MẤT KẾT NỐI',
      'verify_root_cause_title': 'Phân tích Nguyên nhân:',
      'verify_fix_advice_title': 'Hướng dẫn Khắc phục:',
      'verify_btn_quick_fix': '⚡ Sửa Route Nhanh cho IP này',
      'verify_quick_fix_success': 'Đã thêm route thành công vào Windows!',
      'verify_quick_fix_fail':
          'Thêm route thất bại. Vui lòng chạy ứng dụng dưới quyền Administrator.',
      'verify_copy_logs': 'Sao chép Log',
      'verify_logs_copied': 'Đã sao chép nhật ký chẩn đoán vào clipboard!',
      'table_dest': 'Đích (Destination)',
      'table_netmask': 'Netmask',
      'table_gateway': 'Gateway',
      'table_interface': 'Card mạng (Interface)',
      'table_metric': 'Metric',
      'logs_auto_scroll': 'Cuộn tự động',
      'about_sys_info': 'Môi trường Hệ thống & Đồ họa',
      'about_os': 'Hệ điều hành',
      'about_native_graphics': 'Đồ họa Native',
      'about_privilege': 'Quyền thực thi',
      'about_build_time': 'Thời điểm Build',
      'about_debug_mode': 'Chế độ Debug (-debug)',
      'about_license_title': 'Bản quyền & Giấy phép',
      'about_license_desc':
          'Phát triển bởi JA Tech Vietnam. Được phát hành theo Giấy phép Mã nguồn mở MIT License. Bạn có toàn quyền sử dụng, sửa đổi và phân phối ứng dụng này.',
      'settings_glass_title': 'Tùy biến Giao diện Kính mờ',
      'theme_toggle_tooltip': 'Chuyển đổi giao diện Sáng / Tối',
      'lang_quick_btn_tooltip': 'Nhấn để chuyển nhanh ngôn ngữ',
      'steps_running_badge': 'Đang chạy ({done}/{total})',
      'steps_done_badge': 'Hoàn tất ({total}/{total})',
      'steps_total_badge': '{total} Bước tiến trình',
    },
    'en': {
      'app_title': 'Network Route Optimizer',
      'sidebar_home': 'Dashboard',
      'sidebar_config': 'Configuration',
      'sidebar_diag': 'Diagnostics',
      'sidebar_logs': 'System Logs',
      'sidebar_about': 'About App',
      'top_bar_title': 'Connection Diagnostics',
      'admin_mode': 'ADMIN MODE',
      'user_mode': 'USER MODE (REQUIRES ADMIN)',
      'home_welcome': 'Ready to optimize dual-NIC routing',
      'home_welcome_sub':
          'Automatically ignore default routes on the LAN card and inject persistent routing entries for internal resources.',
      'home_btn_fix': 'START FIX',
      'home_steps_title': 'Step-by-step Procedure',
      'config_title': 'Routing Parameters Configuration',
      'config_desc':
          'Configure gateway IPs and subnet parameters to apply onto the active Windows network adapters.',
      'config_internet_gw': 'Primary Internet Gateway (INTERNET_GW)',
      'config_backup_gw': 'Backup Internet Gateway (BACKUP_GW)',
      'config_lan_gw': 'LAN Gateway (LAN_GW)',
      'config_lan_net': 'LAN Destination Subnet (LAN_NET)',
      'config_lan_mask': 'LAN Subnet Mask (LAN_MASK)',
      'config_log_path': 'Log File Output Path',
      'config_custom_routes': 'Additional Target Subnets',
      'config_lan_dest': 'LAN Destination Subnet (IP/Mask)',
      'config_lan_dest_desc':
          'Subnets routed explicitly through the local LAN gateway.',
      'config_internet_dest': 'Internet Bypass Subnet (IP/Mask)',
      'config_internet_dest_desc':
          'Subnets forced explicitly through the Internet gateway.',
      'config_recovery_title': 'System Recovery & Configuration Storage',
      'config_recovery_win': 'Windows System Backup',
      'config_recovery_win_desc':
          'Backup active Windows routes and adapter configuration metrics for restoration.',
      'config_btn_create': 'Create Backup',
      'config_btn_restore': 'Restore System',
      'config_app_json': 'App Configuration JSON',
      'config_app_json_desc':
          'Export current gateway subnets to a JSON file, or import configuration from a saved file.',
      'config_btn_export': 'Export Config',
      'config_btn_import': 'Import Config',
      'config_btn_reset': 'Reset to Default',
      'config_btn_save': 'Save Configuration',
      'config_add_route': 'Add Subnet',
      'config_dialog_admin_req': 'Administrator Rights Required',
      'config_dialog_backup_success':
          'Windows routing configuration snapshot created successfully.',
      'config_dialog_backup_fail':
          'Failed to export backup. Please check logs or run as Admin.',
      'config_dialog_restore_success':
          'Windows network settings restored to selected snapshot successfully.',
      'config_dialog_restore_fail':
          'An error occurred during system restoration. Please check logs.',
      'config_dialog_export_success':
          'Configuration exported successfully to:\n',
      'config_dialog_export_fail':
          'Failed to write configuration file to disk.',
      'config_dialog_import_success':
          'New configuration imported and loaded successfully.',
      'config_dialog_import_fail':
          'Invalid or corrupted configuration JSON file.',
      'config_dialog_save_success':
          'Routing parameters saved successfully to config.json and config.ini.',
      'config_dialog_save_title': 'Configuration Saved',
      'config_btn_detect': 'Auto Detect',
      'config_detect_success': 'Active gateways detected and updated!',
      'config_detect_fail': 'Failed to detect active gateways.',
      'diag_title': 'Quick Diagnostics & Utilities',
      'diag_desc':
          'Execute manual diagnostic tests or perform system network cache flushing.',
      'diag_btn_route': 'Print Routing Table',
      'diag_btn_route_desc':
          'Print the active IPv4 routing table of this machine.',
      'diag_btn_flush': 'Flush DNS & ARP',
      'diag_btn_flush_desc':
          'Clear local DNS cache and physical address mapping table ARP.',
      'diag_btn_tailscale': 'Tailscale Status',
      'diag_btn_tailscale_desc':
          'Check connection status and active peers in Tailscale network.',
      'diag_ping': 'Ping Target:',
      'diag_terminal': 'OUTPUT TERMINAL',
      'diag_table_title': 'DETAILED IPv4 ROUTE LISTING',
      'diag_btn_raw': 'Show Raw Output',
      'diag_btn_table': 'Show Data Table',
      'diag_btn_copy': 'Copy Output',
      'logs_title': 'System Operation Logs',
      'logs_desc': 'View real-time logging output streams of the optimizer.',
      'logs_btn_clear': 'Clear Console',
      'logs_btn_copy': 'Copy Log Stream',
      'about_title': 'About Application',
      'about_desc_title': 'Project Description:',
      'about_details_title': 'PROJECT METADATA CARD',
      'about_name': 'Project Name',
      'about_tech': 'Technology Stack',
      'about_managed': 'Managed By',
      'about_web': 'Website',
      'about_desc_detail': 'Metadata Details',
      'about_project_desc':
          'This application provides a graphical user interface (GUI) to solve default gateway conflicts when a computer connects to two networks simultaneously: the Internet and the company\'s internal network (LAN/Company). \n\nBy enabling "IgnoreDefaultRoutes" on the LAN card interface, Windows ignores incorrect default routes from the LAN DHCP. Additionally, it injects persistent routes to direct LAN subnets via the correct LAN gateway while preserving all other traffic through the main Internet connection.',
      'step_admin': 'Check Administrator privileges',
      'step_lan_adapter': 'Enable IgnoreDefaultRoutes on LAN card (172.21.x)',
      'step_metrics': 'Set priority metrics for Network/Backup (192.168.x)',
      'step_flush': 'Flush ARP & DNS cache',
      'step_clean': 'Clean up obsolete/incorrect routes',
      'step_persistent_routes': 'Inject new persistent routing entries',
      'step_clean_lan_gw': 'Block default route via LAN gateway finally',
      'step_verify': 'Verify current routing table',
      'step_ping_test': 'Verify Internet ping connectivity (1.1.1.1)',
      'step_tailscale_login': 'Check connection to login.tailscale.com:443',
      'step_tailscale_status': 'Check Tailscale client status',
      'logs_btn_export': 'Export Log File',
      'logs_copied_toast': 'System logs copied to clipboard',
      'logs_export_success_toast': 'Logs exported successfully: ',
      'logs_export_fail_toast': 'Failed to export logs',
      'logs_empty_toast': 'No logs to export.',
      'logs_empty_placeholder': 'No system logs available yet.',
      'log_opt_start': '===== START ROUTING OPTIMIZATION PROCESS =====',
      'log_opt_end': '===== ROUTING OPTIMIZATION PROCESS COMPLETED =====',
      'log_engine_missing': 'Platform engine not found.',
      'log_admin_required':
          'Application is not running with Administrator privileges. Please run as Administrator.',
      'log_admin_ok': 'Administrator privileges verified.',
      'log_lan_adapter_warn':
          'WARN: LAN adapter matching {pattern} not found or failed to configure.',
      'log_lan_adapter_ok':
          'Enabled IgnoreDefaultRoutes & set metric 80 for adapter {pattern}',
      'log_metrics_warn':
          'WARN: Adapter {ip1} and {ip2} not found to set metrics',
      'log_metrics_ok':
          'Set priority metrics for Internet adapters (metric 10/25)',
      'log_flush_ok': 'Flushed ARP and DNS cache.',
      'log_clean_ok':
          'Cleaned old/incorrect routes related to {internetGw} and {lanGw}',
      'log_persistent_warn':
          'Adding route 0.0.0.0 via {gw} metric 5 warning (Already exists?)',
      'log_persistent_ok':
          'Persistent routes injected:\n  - Default route: 0.0.0.0/0 -> {internetGw} (Metric 5)\n  - Injected {lanCount} LAN routes (via {lanGw})\n  - Injected {internetCount} Internet-Bypass routes (via {internetGw}, Metric 2)',
      'log_clean_lan_gw_ok': 'Removed all default routes via LAN gateway {gw}',
      'log_verify_warn':
          'WARN: Default route via {gw} still exists. Please run the program again.',
      'log_verify_ok': 'Correct: No default route via {gw}.',
      'log_ping_warn':
          'WARN: Ping 1.1.1.1 failed. Please check network connection.',
      'log_ping_ok': 'Ping 1.1.1.1 OK!\n{res}',
      'log_tailscale_conn_warn':
          'WARN: Failed to connect to login.tailscale.com:443',
      'log_tailscale_conn_ok': 'Connection to login.tailscale.com:443 OK!',
      'log_backup_start': '===== STARTING NETWORK CONFIGURATION BACKUP =====',
      'log_backup_ok':
          '===== NETWORK CONFIGURATION BACKUP SUCCESSFUL: {timestamp} =====',
      'log_backup_fail': '===== NETWORK CONFIGURATION BACKUP FAILED =====',
      'log_restore_start':
          '===== STARTING NETWORK CONFIGURATION RESTORATION: {timestamp} =====',
      'log_restore_config_ok':
          '[OK] Application configuration restored from backup.',
      'log_restore_ok':
          '===== NETWORK CONFIGURATION RESTORATION SUCCESSFUL =====',
      'log_restore_fail':
          '===== NETWORK CONFIGURATION RESTORATION FAILED =====',
      'log_import_ok': '[OK] Imported new configuration from {path}',
      'log_export_ok': '[OK] Exported configuration to {path}',
      'log_load_config_ok':
          'Configuration loaded successfully from config.json',
      'log_load_config_default':
          'config.json not found, using default configuration.',
      'log_save_config_ok': 'Configuration saved to config.json and config.ini',
      'log_rollback_start':
          '===== STARTING AUTOMATIC CONFIGURATION ROLLBACK =====',
      'log_rollback_ok':
          '===== AUTOMATIC CONFIGURATION ROLLBACK SUCCESSFUL =====',
      'log_rollback_fail':
          '===== AUTOMATIC CONFIGURATION ROLLBACK FAILED =====',
      'dialog_cancel': 'Cancel',
      'dialog_confirm': 'Confirm',
      'config_restore_defaults': 'Restore System Defaults',
      'config_restore_defaults_desc':
          'Delete all added static routes, reset network cards to Automatic Metric, and disable IgnoreDefaultRoutes.',
      'config_btn_restore_defaults': 'Restore Defaults',
      'config_dialog_restore_defaults_title': 'Restore System Defaults?',
      'config_dialog_restore_defaults_confirm':
          'This will delete all persistent routes and reset all Windows network adapter metrics to system default. Do you want to proceed?',
      'config_dialog_restore_defaults_success':
          'Windows default network settings restored successfully.',
      'config_dialog_restore_defaults_fail':
          'Failed to restore default settings. Please check logs for details.',
      'profile_title': 'Profile & Network Configuration',
      'profile_active': 'Current Network Profile',
      'profile_default': 'Default',
      'profile_tooltip_add': 'Create new profile',
      'profile_tooltip_delete': 'Delete this profile',
      'profile_create_title': 'Create New Profile',
      'profile_create_label': 'Network profile name',
      'profile_create_hint': 'e.g. Office Network B',
      'auto_heal_title':
          'Auto-Monitoring & Routing Optimization (Auto-Healing)',
      'auto_heal_desc':
          'Monitor routing table every 30s. Auto-fix if Windows resets gateway on network loss or IP change.',
      'auto_heal_badge': 'AUTO-HEAL ACTIVE',
      'gateway_offline': 'Offline',
      'dashboard_live_console': 'Recent Execution Logs',
      'dashboard_console_placeholder':
          'Click "START FIX" to run optimization and view live routing logs here...',
      'badge_dual_routing': 'DUAL NETWORK ROUTING',
      'node_internet_gw': 'Internet GW',
      'node_this_pc': 'This PC',
      'node_lan_gw': 'LAN GW',
      'not_configured': 'Not configured',
      'status_ready': 'READY',
      'status_fixing': 'OPTIMIZING...',
      'status_dual_active': 'DUAL ROUTE ACTIVE',
      'status_standby': 'STANDBY',
      'step_status_idle': 'Pending',
      'step_status_running': 'Running',
      'step_status_success': 'Done',
      'step_status_warning': 'Warning',
      'step_status_error': 'Error',
      'view_all_logs': 'View all',
      'no_logs_placeholder':
          'No logs yet. Click "START FIX" to run network route optimization.',
      'gateways_card_title': 'Routing Gateways',
      'subnets_card_title': 'Subnets & Log File Path',
      'add_btn': 'Add',
      'btn_cancel': 'Cancel',
      'no_custom_routes': 'No custom routes configured.',
      'diag_quick_tools': 'Quick Diagnostic Tools',
      'diag_ping_hint':
          'Enter IP/Host to test ping (e.g. 1.1.1.1 or google.com)',
      'diag_btn_ping': 'Test Ping',
      'diag_port_test': 'Port Connectivity',
      'diag_restore_defaults': 'Restore Windows Defaults',
      'diag_routing_table': 'Windows IPv4 Routing Table',
      'diag_terminal_idle_hint':
          'Ready to run diagnostics. Select a tool above or run a ping test to view results here.',
      'diag_terminal_running': 'Running diagnostic task...',
      'diag_terminal_output_title': 'Diagnostic Output',
      'verify_suite_title': 'Network Verification & Diagnostics',
      'verify_input_hint':
          'Enter IP or Web URL (e.g. 10.21.168.50, google.com, http://erp.local:8080)',
      'verify_btn': 'Verify Now',
      'verify_route_auto': 'Auto',
      'verify_route_lan': 'Via LAN',
      'verify_route_internet': 'Via Internet',
      'verify_status_pass': 'OPTIMAL ROUTE',
      'verify_status_warning': 'FURTHER CHECKS NEEDED',
      'verify_status_misrouted': 'MISROUTED GATEWAY',
      'verify_status_unreachable': 'UNREACHABLE',
      'verify_root_cause_title': 'Root Cause Analysis:',
      'verify_fix_advice_title': 'Recommended Actions:',
      'verify_btn_quick_fix': '⚡ Quick Fix Route for this IP',
      'verify_quick_fix_success': 'Successfully added route to Windows!',
      'verify_quick_fix_fail':
          'Failed to add route. Please run application as Administrator.',
      'verify_copy_logs': 'Copy Log',
      'verify_logs_copied': 'Diagnostic logs copied to clipboard!',
      'table_dest': 'Destination',
      'table_netmask': 'Netmask',
      'table_gateway': 'Gateway',
      'table_interface': 'Interface',
      'table_metric': 'Metric',
      'logs_auto_scroll': 'Auto Scroll',
      'about_sys_info': 'System Environment & Graphics',
      'about_os': 'Operating System',
      'about_native_graphics': 'Native Graphics',
      'about_privilege': 'Privilege',
      'about_build_time': 'Build Timestamp',
      'about_debug_mode': 'Debug Mode (-debug)',
      'about_license_title': 'License & Copyright',
      'about_license_desc':
          'Developed by JA Tech Vietnam. Released under the MIT Open Source License. You are free to use, modify, and distribute this application.',
      'settings_glass_title': 'Glassmorphism Live Tuning',
      'theme_toggle_tooltip': 'Toggle Light / Dark theme',
      'lang_quick_btn_tooltip': 'Click to switch language',
      'steps_running_badge': 'Running ({done}/{total})',
      'steps_done_badge': 'Done ({total}/{total})',
      'steps_total_badge': '{total} Routine Steps',
    },
    'zh': {
      'app_title': '双网关路由优化器',
      'sidebar_home': '主页',
      'sidebar_config': '网络配置',
      'sidebar_diag': '网络诊断',
      'sidebar_logs': '运行日志',
      'sidebar_about': '关于应用',
      'top_bar_title': '连接诊断',
      'admin_mode': '管理员模式',
      'user_mode': '普通用户模式 (需要管理员权限)',
      'home_welcome': '已准备好优化双网关路由',
      'home_welcome_sub': '自动忽略局域网适配器上的默认路由，并为内部资源写入永久静态路由。',
      'home_btn_fix': '开始修复',
      'home_steps_title': '系统执行步骤',
      'config_title': '路由参数配置',
      'config_desc': '设置网关 IP 和子网参数，以正确应用于 Windows 适配器。',
      'config_internet_gw': '主互联网网关 (INTERNET_GW)',
      'config_backup_gw': '备用互联网网关 (BACKUP_GW)',
      'config_lan_gw': '局域网网关 (LAN_GW)',
      'config_lan_net': '局域网目标网段 (LAN_NET)',
      'config_lan_mask': '局域网子网掩码 (LAN_MASK)',
      'config_log_path': '日志文件输出路径',
      'config_custom_routes': '附加目标路由网段',
      'config_lan_dest': '目标局域网段 (IP/Mask)',
      'config_lan_dest_desc': '显式通过局域网网关路由的子网段。',
      'config_internet_dest': '互联网绕行网段 (IP/Mask)',
      'config_internet_dest_desc': '显式通过主互联网网关路由的子网段。',
      'config_recovery_title': '系统还原点与配置备份',
      'config_recovery_win': 'Windows 系统还原点',
      'config_recovery_win_desc': '备份 Windows 当前静态路由和适配器属性以供故障恢复。',
      'config_btn_create': '创建还原点',
      'config_btn_restore': '系统还原',
      'config_app_json': '应用程序 JSON 配置',
      'config_app_json_desc': '将当前网关和自定义网段导出为 JSON 文件，或从保存的文件中导入配置。',
      'config_btn_export': '导出 JSON 配置',
      'config_btn_import': '导入 JSON 配置',
      'config_btn_reset': '重置默认值',
      'config_btn_save': '保存当前配置',
      'config_add_route': '添加网段',
      'config_dialog_admin_req': '需要管理员权限',
      'config_dialog_backup_success': 'Windows 路由状态还原点备份成功。',
      'config_dialog_backup_fail': '无法导出备份。请检查日志或以管理员身份运行。',
      'config_dialog_restore_success': 'Windows 网络设置已成功恢复到选定的还原点。',
      'config_dialog_restore_fail': '还原过程中出错。请检查日志。',
      'config_dialog_export_success': '配置文件已成功保存至:\n',
      'config_dialog_export_fail': '写入配置文件至磁盘失败。',
      'config_dialog_import_success': '新配置已成功导入并应用。',
      'config_dialog_import_fail': '无效或损坏的 JSON 配置文件。',
      'config_dialog_save_success': '路由参数已成功保存至 config.json 和 config.ini。',
      'config_dialog_save_title': '配置已保存',
      'config_btn_detect': '自动检测',
      'config_detect_success': '已自动检测并更新网关！',
      'config_detect_fail': '无法自动检测活动网关。',
      'diag_title': '网络诊断与系统清理',
      'diag_desc': '执行手动连接诊断或快速清除系统网络缓存。',
      'diag_btn_route': '查看活动路由表',
      'diag_btn_route_desc': '打印此计算机当前处于活动状态 of IPv4 路由表。',
      'diag_btn_flush': '清除 DNS 和 ARP 缓存',
      'diag_btn_flush_desc': '清空系统 local DNS 缓存以及物理地址解析 ARP 缓存。',
      'diag_btn_tailscale': 'Tailscale VPN 状态',
      'diag_btn_tailscale_desc': '检查 Tailscale 虚拟网段中的连接状态和活动对等节点。',
      'diag_ping': 'Ping 测试目标:',
      'diag_terminal': 'OUTPUT TERMINAL',
      'diag_table_title': '详细 IPv4 路由列表',
      'diag_btn_raw': '显示原始文本',
      'diag_btn_table': '显示结构化表格',
      'diag_btn_copy': '复制输出结果',
      'logs_title': '系统运行日志',
      'logs_desc': '查看双网关优化器运行 of 实时日志流。',
      'logs_btn_clear': '清空日志',
      'logs_btn_copy': '复制日志',
      'about_title': '关于应用程序',
      'about_desc_title': '项目说明:',
      'about_details_title': '项目元数据卡',
      'about_name': '项目名称',
      'about_tech': '技术栈',
      'about_managed': '维护管理者',
      'about_web': '官方网站',
      'about_desc_detail': '元数据详情',
      'about_project_desc':
          '该应用程序提供图形用户 interface (GUI)，以彻底解决计算机同时连接两个网络 (互联网和公司局域网 LAN/Company) 时的默认网关冲突。 \n\n通过在局域网网卡上启用 "IgnoreDefaultRoutes"，Windows 将忽略来自局域网 DHCP 的错误默认路由。此外，它写入永久静态路由，以将局域网段引导至正确的局域网网关，同时保留所有其他流量通过主互联网网关。',
      'step_admin': '检查管理员权限',
      'step_lan_adapter': '在局域网网卡上启用忽略默认路由 (172.21.x)',
      'step_metrics': '设置网络/备份接口的优先跃点数 (192.168.x)',
      'step_flush': '清除 ARP 和 DNS 缓存',
      'step_clean': '清理过时/错误的路由',
      'step_persistent_routes': '写入新的永久静态路由',
      'step_clean_lan_gw': '最后阻止通过局域网网关的默认路由',
      'step_verify': '验证当前活动路由表',
      'step_ping_test': '测试互联网 Ping 连通性 (1.1.1.1)',
      'step_tailscale_login': '检查与 login.tailscale.com:443 的连接',
      'step_tailscale_status': '检查 Tailscale 客户端运行状态',
      'logs_btn_export': '导出日志文件',
      'logs_copied_toast': '系统日志已复制到剪贴板',
      'logs_export_success_toast': '日志导出成功: ',
      'logs_export_fail_toast': '导出日志失败',
      'logs_empty_toast': '没有可导出的日志。',
      'logs_empty_placeholder': '暂无系统日志。',
      'log_opt_start': '===== 开始网络路由优化流程 =====',
      'log_opt_end': '===== 网络路由优化流程已完成 =====',
      'log_engine_missing': '未找到平台引擎。',
      'log_admin_required': '应用程序未以管理员权限运行。请以管理员身份重新运行。',
      'log_admin_ok': '已验证管理员权限。',
      'log_lan_adapter_warn': '警告: 未找到匹配 {pattern} 的局域网网卡或配置失败。',
      'log_lan_adapter_ok': '已为适配器 {pattern} 启用 IgnoreDefaultRoutes 并设置跃点数 80',
      'log_metrics_warn': '警告: 未找到适配器 {ip1} 和 {ip2} 以设置跃点数',
      'log_metrics_ok': '已为互联网适配器设置优先跃点数 (跃点数 10/25)',
      'log_flush_ok': '已清除 ARP 和 DNS 缓存。',
      'log_clean_ok': '已清理与 {internetGw} 和 {lanGw} 相关的过时/错误路由',
      'log_persistent_warn': '通过 {gw} 添加路由 0.0.0.0 跃点数 5 警告 (是否已存在？)',
      'log_persistent_ok':
          '已写入永久路由:\n  - 默认路由: 0.0.0.0/0 -> {internetGw} (跃点数 5)\n  - 已写入 {lanCount} 条局域网路由 (通过 {lanGw})\n  - 已写入 {internetCount} 条互联网绕行路由 (通过 {internetGw}, 跃点数 2)',
      'log_clean_lan_gw_ok': '已删除所有通过局域网网关 {gw} 的默认路由',
      'log_verify_warn': '警告: 仍然存在通过 {gw} 的默认路由。请重新运行程序。',
      'log_verify_ok': '正确: 不存在通过 {gw} 的默认路由。',
      'log_ping_warn': '警告: Ping 1.1.1.1 失败。请检查网络连接。',
      'log_ping_ok': 'Ping 1.1.1.1 成功！\n{res}',
      'log_tailscale_conn_warn': '警告: 无法连接至 login.tailscale.com:443',
      'log_tailscale_conn_ok': '连接至 login.tailscale.com:443 成功！',
      'log_backup_start': '===== 开始备份网络配置 =====',
      'log_backup_ok': '===== 网络配置备份成功: {timestamp} =====',
      'log_backup_fail': '===== 网络配置备份失败 =====',
      'log_restore_start': '===== 开始恢复网络配置: {timestamp} =====',
      'log_restore_config_ok': '[OK] 已从备份中恢复应用配置。',
      'log_restore_ok': '===== 网络配置恢复成功 =====',
      'log_restore_fail': '===== 网络配置恢复失败 =====',
      'log_import_ok': '[OK] 已从 {path} 导入新配置',
      'log_export_ok': '[OK] 已将配置导出至 {path}',
      'log_load_config_ok': '成功从 config.json 加载配置',
      'log_load_config_default': '未找到 config.json，使用默认配置。',
      'log_save_config_ok': '配置已保存至 config.json 和 config.ini',
      'log_rollback_start': '===== 开始自动配置回滚 (ROLLBACK) =====',
      'log_rollback_ok': '===== 自动配置回滚成功 =====',
      'log_rollback_fail': '===== 自动配置回滚失败 =====',
      'dialog_cancel': '取消',
      'dialog_confirm': '确认',
      'config_restore_defaults': '恢复系统默认设置',
      'config_restore_defaults_desc':
          '删除所有添加的静态路由，将网卡重置为自动跃点数，并禁用 IgnoreDefaultRoutes。',
      'config_btn_restore_defaults': '恢复默认设置',
      'config_dialog_restore_defaults_title': '恢复系统默认设置？',
      'config_dialog_restore_defaults_confirm':
          '此操作将删除所有永久路由，并将所有 Windows 网络适配器跃点数重置为系统默认值。是否继续？',
      'config_dialog_restore_defaults_success': '已成功恢复 Windows 默认 network 设置。',
      'config_dialog_restore_defaults_fail': '恢复默认设置失败。请检查日志以获取详细信息。',
      'profile_title': '配置与网络配置文件 (Profiles)',
      'profile_active': '当前网络配置',
      'profile_default': '默认',
      'profile_tooltip_add': '创建新配置',
      'profile_tooltip_delete': '删除此配置',
      'profile_create_title': '创建新配置',
      'profile_create_label': '网络配置名称',
      'profile_create_hint': '例如：办公室网络 B',
      'auto_heal_title': '自动监控与路由优化 (自动修复)',
      'auto_heal_desc': '每30秒监控一次路由表。如果 Windows 在断网或 IP 更改时重置网关，则自动修复。',
      'auto_heal_badge': '自动修复已激活',
      'gateway_offline': '离线',
      'gateway_local_ip': '本地 IP',
      'dashboard_live_console': '近期执行日志',
      'dashboard_console_placeholder': '点击 “开始修复” 运行优化并在此处查看实时路由日志...',
      'badge_dual_routing': 'DUAL NETWORK ROUTING',
      'node_internet_gw': '互联网网关',
      'node_this_pc': '此计算机',
      'node_lan_gw': '局域网网关',
      'not_configured': '未配置',
      'status_ready': '就绪',
      'status_fixing': '优化中...',
      'status_dual_active': '双网路由已激活',
      'status_standby': '待机',
      'step_status_idle': '等待',
      'step_status_running': '处理中',
      'step_status_success': '完成',
      'step_status_warning': '警告',
      'step_status_error': '错误',
      'view_all_logs': '查看全部',
      'no_logs_placeholder': '尚无日志。点击“开始修复”运行网络路由优化。',
      'gateways_card_title': '路由网关设置',
      'subnets_card_title': '子网与日志路径',
      'add_btn': '添加',
      'btn_cancel': '取消',
      'no_custom_routes': '未配置自定义路由。',
      'diag_quick_tools': '快速诊断工具',
      'diag_ping_hint': '输入 IP/Host 测试 ping (例如: 1.1.1.1 或 google.com)',
      'diag_btn_ping': 'Ping 测试',
      'diag_port_test': '测试服务器端口',
      'diag_restore_defaults': '恢复 Windows 默认',
      'diag_routing_table': 'Windows IPv4 路由表',
      'diag_terminal_idle_hint': '诊断已就绪。点击上方工具或运行 ping 测试以在此查看详细结果。',
      'diag_terminal_running': '正在执行诊断任务...',
      'diag_terminal_output_title': '诊断输出结果',
      'verify_suite_title': '网络验证与路由诊断',
      'verify_input_hint':
          '输入 IP 或网页 URL (例如: 10.21.168.50, google.com, http://erp.local:8080)',
      'verify_btn': '立即验证',
      'verify_route_auto': '自动',
      'verify_route_lan': '走局域网',
      'verify_route_internet': '走外网',
      'verify_status_pass': '路由通畅',
      'verify_status_warning': '需要进一步检查',
      'verify_status_misrouted': '网关路由异常',
      'verify_status_unreachable': '连接超时',
      'verify_root_cause_title': '问题诊断分析:',
      'verify_fix_advice_title': '解决建议:',
      'verify_btn_quick_fix': '⚡ 快速修复此 IP 路由',
      'verify_quick_fix_success': '已成功向 Windows 添加路由！',
      'verify_quick_fix_fail': '添加路由失败。请以管理员身份运行。',
      'verify_copy_logs': '复制日志',
      'verify_logs_copied': '诊断日志已复制到剪贴板！',
      'table_dest': '目标网络',
      'table_netmask': '网络掩码',
      'table_gateway': '网关',
      'table_interface': '网络接口',
      'table_metric': '跃点数',
      'logs_auto_scroll': '自动滚动',
      'about_sys_info': '系统与图形环境',
      'about_os': '操作系统',
      'about_native_graphics': '原生图形效果',
      'about_privilege': '运行权限',
      'about_build_time': '编译时间',
      'about_debug_mode': '调试模式 (-debug)',
      'about_license_title': '版权与开源许可证',
      'about_license_desc':
          '由 JA Tech Vietnam 开发。基于 MIT 开源许可证发布。您可以自由使用、修改和分发此应用程序。',
      'settings_glass_title': '毛玻璃界面实时调整',
      'theme_toggle_tooltip': '切换明亮 / 暗黑主题',
      'lang_quick_btn_tooltip': '点击快速切换语言',
      'steps_running_badge': '运行中 ({done}/{total})',
      'steps_done_badge': '完成 ({total}/{total})',
      'steps_total_badge': '{total} 项步骤',
    },
  };

  String get(String key) {
    return _localizedValues[lang]?[key] ?? _localizedValues['vi']?[key] ?? key;
  }

  String getWithParams(String key, Map<String, String> params) {
    String value = get(key);
    params.forEach((k, v) {
      value = value.replaceAll('{$k}', v);
    });
    return value;
  }
}
